services:
  microbin:
    build: . # build by yourself
    restart: always
    ports:
      - "${MICROBIN_PORT}:8080"
    volumes:
      - ./microbin-data:/app/microbin_data
    env_file:
      - .env
