services:
  microbin:
    image: ghcr.io/zhaobenny/microbin:latest
    restart: always
    ports:
      - "${MICROBIN_PORT}:8080"
    volumes:
      - ./microbin-data:/app/microbin_data
    env_file:
      - .env
